// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMWlAOqNMIEjoGlpdD13pmt8Vz_UJFjhU',
    appId: '1:537077339232:web:528401e880cf1a93e35f05',
    messagingSenderId: '537077339232',
    projectId: 'mylaundry-1877c',
    authDomain: 'mylaundry-1877c.firebaseapp.com',
    storageBucket: 'mylaundry-1877c.firebasestorage.app',
    measurementId: 'G-2SJHH3B8S4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKg-kjo63lKUZdbmkPgi7jVYmcoByWNE4',
    appId: '1:537077339232:android:db5f431e625a2c56e35f05',
    messagingSenderId: '537077339232',
    projectId: 'mylaundry-1877c',
    storageBucket: 'mylaundry-1877c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBldrQ--HzRY9Cm7CFb9E9ixWaZ3NI6hFQ',
    appId: '1:537077339232:ios:f039391b25697e29e35f05',
    messagingSenderId: '537077339232',
    projectId: 'mylaundry-1877c',
    storageBucket: 'mylaundry-1877c.firebasestorage.app',
    iosBundleId: 'com.example.myLaundry',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBldrQ--HzRY9Cm7CFb9E9ixWaZ3NI6hFQ',
    appId: '1:537077339232:ios:f039391b25697e29e35f05',
    messagingSenderId: '537077339232',
    projectId: 'mylaundry-1877c',
    storageBucket: 'mylaundry-1877c.firebasestorage.app',
    iosBundleId: 'com.example.myLaundry',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMWlAOqNMIEjoGlpdD13pmt8Vz_UJFjhU',
    appId: '1:537077339232:web:ca32a8a45a4ea835e35f05',
    messagingSenderId: '537077339232',
    projectId: 'mylaundry-1877c',
    authDomain: 'mylaundry-1877c.firebaseapp.com',
    storageBucket: 'mylaundry-1877c.firebasestorage.app',
    measurementId: 'G-WSHMLR613G',
  );
}
